os:
  mail:
    # 邮件服务器的SMTP地址 默认：126
#    host: smtp.126.com
    # 邮件服务器的SMTP端口 默认：25
#    port: 25
    # 发件人（必须正确，否则发送失败）
    from:
    # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
    user:
    # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
    pass:
    #使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。
#    starttlsEnable: true
    # 使用SSL安全连接
#    sslEnable: false
  seq:
    # 序号规则模板 {bizFlag}{date}{seq}三元素组合，默认值{bizFlag}{date}{seq}
    # bizFlag业务部分标识：序号规则模板中做前缀可以为字母和数字，中间建议为数字，通过传入bizFlag参数取得不同业务模块序号
    template: "{bizFlag}{date}{seq}"
    # 日期部分格式：yyyyMMdd/yyMMdd/yyyyMMddHHmmss，可以缺省此项配置，默认值：yyyyMMdd
    dateFormat: "yyyyMMdd"
    # 序号部分长度：可以缺省此项配置，默认值：6
    seqLength: 6
    # 使用redis
    useRedis: true